version: "3"
services:
  redis:
    container_name: redis
    image: redis
    # networks:
    #   RuoYu:
    #     ipv4_address: 172.20.0.2
    command: redis-server --requirepass root
    labels:
      createdBy: Apps
    ports:
      - 6379:6379

# networks:
#   RuoYu:
#     external: true
